name: Run Tests with Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      - name: Run tests with coverage
        run: |
          coverage run --branch -m unittest  # Run tests using coverage with branch option

      - name: Generate a coverage report
        run: |
          coverage report  # Generate a plain text coverage report

      - name: Upload coverage report (optional)
        run: |
          coverage html  # Generate an HTML report (optional)
